Testing for fmt output meticulously...

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -34,4 +34,11 @@ jobs:
           go-version: "1.23.0"
     
       - name: Format codebase
-        run: go fmt ./...
+        id: go-fmt-check
+        run: |
+          OUTPUT=$(go fmt ./...)
+          if [ -n "$OUTPUT" ]; then
+            echo "::error::Go fmt found unformatted files:"
+            echo "$OUTPUT"
+            exit 1
+          fi
